spring.application.name=chatapp
spring.data.mongodb.uri=mongodb+srv://akankshamokashe8_db_user:Akanksha04@cluster0.zyd5swy.mongodb.net/chatdb?retryWrites=true&w=majority
server.port=8080
server.address=127.0.0.1
